name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write  # Required for creating GitHub Releases

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore app/app.csproj

      - name: Build
        run: dotnet build app/app.csproj --no-restore --configuration Release

      - name: Test
        run: dotnet test app/app.csproj --no-build --configuration Release

      - name: Publish App
        run: dotnet publish app/app.csproj --configuration Release --output ./publish

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: ./publish

  release:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: published-app
          path: ./publish

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.run_number }}
          tag_name: v1.${{ github.run_number }}
          body: "Automated release from CI"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ./publish/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
