name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write  # Required for creating GitHub Releases

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore App/App.csproj

      - name: Build
        run: dotnet build App/App.csproj --no-restore --configuration Release

      - name: Test
        run: dotnet test App/App.csproj --no-build --configuration Release

      - name: Publish App
        run: dotnet publish App/App.csproj --configuration Release --output ./publish

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: ./publish

  release:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: published-app
          path: ./publish

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Create Git Tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag v${{ steps.date.outputs.date }}
          git push origin v${{ steps.date.outputs.date }}
  
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.date.outputs.date }}
          tag_name: v${{ steps.date.outputs.date }}
          body: "Automated release from CI"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.date.outputs.date }}
          files: ./publish/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
